name: Manually triggered workflow

on:
  # push:
  workflow_dispatch:

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  workflow_run_info:
    name: Information about the workflow run
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Show Information
        run: |
          echo "This workflow run is triggered by ${{ github.event_name }} ."
          echo " *****************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo " *****************************************************************************"

  backup-archives:
    name: Backup archives
    runs-on: ubuntu-latest
    steps:
      - name: Check system information
        run: |
          set -ex
          pwd
          whoami
          mount
          printenv | sort
          df -h
          ps axf
      - name: Create big file
        run: |
          dd if=/dev/urandom of=smallfile.dat bs=1M count=1
          dd if=/dev/urandom of=bigfile.dat bs=1M count=256
          ls -la
          md5sum *.dat
      - name: Check archive
        run: |
          ls -la
          md5sum *.dat        
      - name: Upload archive to dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: smallfile.dat
          dest: "/apps/arol-backup/smallfile.dat"
          mode: add
          autorename: true
        
# EOF
